spring:
  main:
    # 以不占用端口方式启动 没有线程运行自动关闭应用
    web-application-type: none
  application:
    name: qqbot
  jackson:
    time-zone: GMT+8
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
  http:
    connect-time-out: 6
    read-time-out: 6
    write-time-out: 6
    max-connection: 1000
    max-request: 100
    max-per-host-request: 30
  profiles:
    active: dev
logging:
  file:
    path: ${file.config.log-dir}/${spring.application.name}
  level:
    org: warn
    com: warn
    i: warn
    io: warn
    reactor: warn
    com.zsh: info
    okhttp3:
      OkHttpClient: error
    net.mamoe.mirai.Bot: debug
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
file:
  config:
    qq-device-dir: D:\coderLife\githubProject\qqbot\src\main\resources\device\
    qq-cache-dir: D:\coderLife\githubProject\qqbot\build\cache
    log-dir: /home/logs